_loadouts = [
	["Freizeit (Unbewaffnet)", "Default.sqf"],
	["Soldat","Soldier.sqf"],
	["Grenadier","Grenade.sqf"],
	["Sanitäter (Kämpfer)","MedicCombat.sqf"],
	["Sanitäter (Funk)","MedicRadio.sqf"],
	["Truppführer","Teamleader.sqf"],
	["Truppführer (Funk)","TeamleaderRadio.sqf"],
	["Automatikschütze (Mk200)","Belt_AutoriflemanMk200.sqf"],
	["Automatikschütze (Navid 9.3mm) DLC","Belt_AutoriflemanNavid.sqf"],
	["Gruppenscharfschütze (MK18)","GroupSniperMk18.sqf"],
	["Gruppenscharfschütze (MK14) DLC","GroupSniperMk14.sqf"],
	["Gruppenscharfschütze (MK1) DLC","GroupSniperMk1.sqf"],
	["NLAW (AT)","NLAW.sqf"],
	["Titan (AT)","TitanAT.sqf"],
	["Titan (AA)","TitanAA.sqf"],
	["Sprengstoffexperte","EngineerMine.sqf"],
	["Reparaturexperte","EngineerRepair.sqf"],
	["Aufklärungsexperte","EngineerScout.sqf"],
	["Crew","Crew.sqf"],
	["Helipilot", "HeliPilot.sqf"],
	["Heli Crewchief (Radio)", "HeliCrewchief.sqf"],
	["Jetpilot", "JetPilot.sqf"],
	["Operator HALO", "OperatorHalo.sqf"],
	["Operator HALO (TF) ", "OperatorHaloTF.sqf"],
	["Operator HALO (AT)", "OperatorHaloAT.sqf"],
	["Operator UAV","OperatorUAV.sqf"],
	["Operator Aufklärer","OperatorScout.sqf"],
	["Operator MG (SPMG .338) DLC","OperatorSPMG.sqf"],
	["Operator GS (MAR10 .338) DLC","OperatorMAR10.sqf"],
	["Scharfschütze (M320 LLR)","SniperGM6.sqf"],
	["Scharfschütze (Spotter)","Spotter.sqf"],
	["Scharfschütze (Cyrus) DLC","SniperCyrus.sqf"],
	["Scharfschütze (Spotter) DLC","SpotterDLC.sqf"]
];
