#define GRID_ABS_W		0.5
#define GRID_ABS_H		0.5
#define GRID_TITLE_H 	0.05
#define GRID_COUNT_W 	10
#define GRID_COUNT_H 	10

/* Automatisch zentriert berechnen */
#define GRID_W			(GRID_ABS_W / GRID_COUNT_W)
#define GRID_H			(GRID_ABS_H / GRID_COUNT_H)
#define GRID_ABS_X		(GRID_ABS_W / 2)
#define GRID_ABS_Y		(GRID_ABS_H / 2)



/* ID's 850-899 */
#define PIXLOGISTIC_IDD_DIALOG_HQTELEPORT					950
#define PIXLOGISTIC_IDC_DIALOG_HQTELEPORT_Title 			951
#define PIXLOGISTIC_IDC_DIALOG_HQTELEPORT_SubTitle 			952
#define PIXLOGISTIC_IDC_DIALOG_HQTELEPORT_List 				953
#define PIXLOGISTIC_IDC_DIALOG_HQTELEPORT_ButtonOK			954
#define PIXLOGISTIC_IDC_DIALOG_HQTELEPORT_ButtonCancel 		955
