fnc_Admin_IsPlayerAdmin = compile preprocessFileLineNumbers "admin\functions\fn_IsPlayerAdmin.sqf";
fnc_Admin_ShowDialog = compile preprocessFileLineNumbers "admin\functions\fn_ShowDialog.sqf";
fnc_Admin_RallyTeleportCond = compile preprocessFileLineNumbers "admin\functions\fn_RallyTeleportCond.sqf";
fnc_Admin_RallyTeleportScript = compile preprocessFileLineNumbers "admin\functions\fn_RallyTeleportScript.sqf";
fnc_Admin_TeleportScript = compile preprocessFileLineNumbers "admin\functions\fn_TeleportScript.sqf";
fnc_Admin_GpsScript = compile preprocessFileLineNumbers "admin\functions\fn_GpsScript.sqf";
fnc_Admin_VehicleRemoveScript = compile preprocessFileLineNumbers "admin\functions\fn_VehicleRemoveScript.sqf";
fnc_Admin_VehicleAddScript = compile preprocessFileLineNumbers "admin\functions\fn_VehicleAddScript.sqf";
fnc_Admin_VehiclesSaveScript = compile preprocessFileLineNumbers "admin\functions\fn_VehiclesSaveScript.sqf";
fnc_Admin_TownsSaveScript = compile preprocessFileLineNumbers "admin\functions\fn_TownsSaveScript.sqf";
fnc_Admin_TownStatusScript = compile preprocessFileLineNumbers "admin\functions\fn_TownStatusScript.sqf";
fnc_Admin_TownStatusScript2 = compile preprocessFileLineNumbers "admin\functions\fn_TownStatusScript2.sqf"; // wird von fnc_Admin_TownStatusScript verwendet
fnc_Admin_InfoStatusScript = compile preprocessFileLineNumbers "admin\functions\fn_InfoStatusScript.sqf";