#define GRID_ABS_W		0.5
#define GRID_ABS_H		0.5
#define GRID_TITLE_H 	0.05
#define GRID_COUNT_W 	10
#define GRID_COUNT_H 	10

/* Automatisch zentriert berechnen */
#define GRID_W			(GRID_ABS_W / GRID_COUNT_W)
#define GRID_H			(GRID_ABS_H / GRID_COUNT_H)
#define GRID_ABS_X		(GRID_ABS_W / 2)
#define GRID_ABS_Y		(GRID_ABS_H / 2)



/* ID's 850-899 */
#define PIXLOGISTIC_IDD_DIALOG_BARRACK					850
#define PIXLOGISTIC_IDC_DIALOG_BARRACK_Title 			851
#define PIXLOGISTIC_IDC_DIALOG_BARRACK_SubTitle 		852
#define PIXLOGISTIC_IDC_DIALOG_BARRACK_List 			853
#define PIXLOGISTIC_IDC_DIALOG_BARRACK_ButtonOK			854
#define PIXLOGISTIC_IDC_DIALOG_BARRACK_ButtonCancel 	855
#define PIXLOGISTIC_IDC_DIALOG_BARRACK_ButtonFold	 	856