//diag_log format["X39_MedSys_var_Keys: %1", X39_MedSys_var_Keys],
diag_log "---------- ListVarsDetails ----------";
diag_log format["X39_MedSys_var_Action_CheckUnit_OutputRealValues: %1", X39_MedSys_var_Action_CheckUnit_OutputRealValues],
diag_log format["X39_MedSys_var_BandageBleedingHeal: %1", X39_MedSys_var_BandageBleedingHeal];
diag_log format["X39_MedSys_var_Bleeding_Allow: %1", X39_MedSys_var_Bleeding_Allow];
diag_log format["X39_MedSys_var_Bleeding_BloodLossPerTickModificator: %1", X39_MedSys_var_Bleeding_BloodLossPerTickModificator];
diag_log format["X39_MedSys_var_Bleeding_StartBloodAtMinDamageValueX	: %1", X39_MedSys_var_Bleeding_StartBloodAtMinDamageValueX],
diag_log format["X39_MedSys_var_Bleeding_StartBloodAtMinDamageValueX: %1", X39_MedSys_var_Bleeding_StartBloodAtMinDamageValueX];
diag_log format["X39_MedSys_var_Bleeding_StartingBlood: %1", X39_MedSys_var_Bleeding_StartingBlood];
diag_log format["X39_MedSys_var_Bleeding_Tourniquet_DamagePerTick: %1", X39_MedSys_var_Bleeding_Tourniquet_DamagePerTick],
diag_log format["X39_MedSys_var_Bleeding_Tourniquet_DamagePerTick: %1", X39_MedSys_var_Bleeding_Tourniquet_DamagePerTick];
diag_log format["X39_MedSys_var_Bleeding_maxBleeding: %1", X39_MedSys_var_Bleeding_maxBleeding],
diag_log format["X39_MedSys_var_BloodPackValue: %1", X39_MedSys_var_BloodPackValue];
diag_log format["X39_MedSys_var_DamageMultiplicator: %1", X39_MedSys_var_DamageMultiplicator],		
diag_log format["X39_MedSys_var_Display_BlackOut_FadeManipulator: %1", X39_MedSys_var_Display_BlackOut_FadeManipulator];
diag_log format["X39_MedSys_var_Display_BlackOut_FadeTime_RandomMinMax: %1", X39_MedSys_var_Display_BlackOut_FadeTime_RandomMinMax];
diag_log format["X39_MedSys_var_Display_BlackOut_FadeTime_Value: %1", X39_MedSys_var_Display_BlackOut_FadeTime_Value];
diag_log format["X39_MedSys_var_Display_BlackOut_MaxFade: %1", X39_MedSys_var_Display_BlackOut_MaxFade];
diag_log format["X39_MedSys_var_Display_BlackOut_Open: %1", X39_MedSys_var_Display_BlackOut_Open],
diag_log format["X39_MedSys_var_Display_Overlay_AllowBoodView: %1", X39_MedSys_var_Display_Overlay_AllowBoodView],
diag_log format["X39_MedSys_var_Display_Overlay_AllowHealthView: %1", X39_MedSys_var_Display_Overlay_AllowHealthView],
diag_log format["X39_MedSys_var_Display_Overlay_AllowLegView: %1", X39_MedSys_var_Display_Overlay_AllowLegView],
diag_log format["X39_MedSys_var_Display_Overlay_AllowMorphineView: %1", X39_MedSys_var_Display_Overlay_AllowMorphineView],
diag_log format["X39_MedSys_var_Display_Overlay_AllowTourniquetView: %1", X39_MedSys_var_Display_Overlay_AllowTourniquetView],
diag_log format["X39_MedSys_var_Display_Overlay_EnableBoodView: %1", X39_MedSys_var_Display_Overlay_EnableBoodView];
diag_log format["X39_MedSys_var_Display_Overlay_EnableHealthView: %1", X39_MedSys_var_Display_Overlay_EnableHealthView];
diag_log format["X39_MedSys_var_Display_Overlay_EnableLegView: %1", X39_MedSys_var_Display_Overlay_EnableLegView];
diag_log format["X39_MedSys_var_Display_Overlay_EnableMorphineView: %1", X39_MedSys_var_Display_Overlay_EnableMorphineView];
diag_log format["X39_MedSys_var_Display_TimeBeforeRespawnAvailable_Death: %1", X39_MedSys_var_Display_TimeBeforeRespawnAvailable_Death];
diag_log format["X39_MedSys_var_Display_TimeBeforeRespawnAvailable_NormalKnockout: %1", X39_MedSys_var_Display_TimeBeforeRespawnAvailable_NormalKnockout];
diag_log format["X39_MedSys_var_Generic_DamageBeforeDead: %1", X39_MedSys_var_Generic_DamageBeforeDead];
diag_log format["X39_MedSys_var_Generic_DamageBeforeKnockOut: %1", X39_MedSys_var_Generic_DamageBeforeKnockOut];
diag_log format["X39_MedSys_var_Generic_DamageBeforePermaKnockOut: %1", X39_MedSys_var_Generic_DamageBeforePermaKnockOut],
diag_log format["X39_MedSys_var_Generic_DamageBeforePermaKnockOut: %1", X39_MedSys_var_Generic_DamageBeforePermaKnockOut];
diag_log format["X39_MedSys_var_Head_HeadShotFakeKilling: %1", X39_MedSys_var_Head_HeadShotFakeKilling],
diag_log format["X39_MedSys_var_Healing_BandageHealValue: %1", X39_MedSys_var_Healing_BandageHealValue];
diag_log format["X39_MedSys_var_Healing_BloodPackValue: %1", X39_MedSys_var_Healing_BloodPackValue];
diag_log format["X39_MedSys_var_Healing_MedKitValue: %1", X39_MedSys_var_Healing_MedKitValue];
diag_log format["X39_MedSys_var_Hearing_CureValue: %1", X39_MedSys_var_Hearing_CureValue],
diag_log format["X39_MedSys_var_Hearing_Multiplicator: %1", X39_MedSys_var_Hearing_Multiplicator],
diag_log format["X39_MedSys_var_Hearing_earPlugManipulationValue: %1", X39_MedSys_var_Hearing_earPlugManipulationValue],
diag_log format["X39_MedSys_var_Hearing_enable: %1", X39_MedSys_var_Hearing_enable],
diag_log format["X39_MedSys_var_KillUnitWhenMaxDamageReached: %1", X39_MedSys_var_KillUnitWhenMaxDamageReached],
diag_log format["X39_MedSys_var_KnockOut_MinTimeBetweenTempKnockOuts	: %1", X39_MedSys_var_KnockOut_MinTimeBetweenTempKnockOuts],
diag_log format["X39_MedSys_var_KnockOut_enableChatWhenKnockedOut: %1", X39_MedSys_var_KnockOut_enableChatWhenKnockedOut],
diag_log format["X39_MedSys_var_KnockOut_showAbortButton: %1", X39_MedSys_var_KnockOut_showAbortButton],
diag_log format["X39_MedSys_var_KnockOut_showRespawnButton: %1", X39_MedSys_var_KnockOut_showRespawnButton],
diag_log format["X39_MedSys_var_Legs_DamageBeforeProneOnly: %1", X39_MedSys_var_Legs_DamageBeforeProneOnly];
diag_log format["X39_MedSys_var_Legs_DamageMultiplicator: %1", X39_MedSys_var_Legs_DamageMultiplicator],
diag_log format["X39_MedSys_var_Legs_DamageMultiplicator: %1", X39_MedSys_var_Legs_DamageMultiplicator];
diag_log format["X39_MedSys_var_LifeTime: %1", X39_MedSys_var_LifeTime];
diag_log format["X39_MedSys_var_Limitations: %1", X39_MedSys_var_Limitations],
diag_log format["X39_MedSys_var_Limitations_MaxHeal: %1", X39_MedSys_var_Limitations_MaxHeal],
diag_log format["X39_MedSys_var_Limitations_allowBloodTransfusionInField: %1", X39_MedSys_var_Limitations_allowBloodTransfusionInField],
diag_log format["X39_MedSys_var_Limitations_allowHealingHeadInField: %1", X39_MedSys_var_Limitations_allowHealingHeadInField],
diag_log format["X39_MedSys_var_Limitations_allowHealingLegsInField: %1", X39_MedSys_var_Limitations_allowHealingLegsInField],			
diag_log format["X39_MedSys_var_Limitations_enable: %1", X39_MedSys_var_Limitations_enable],
diag_log format["X39_MedSys_var_MedicalMenu_PullUnitFromVehicle_TempObjectsPlaceholder	: %1", X39_MedSys_var_MedicalMenu_PullUnitFromVehicle_TempObjectsPlaceholder],
diag_log format["X39_MedSys_var_MedicalMenu_PutUnitIntoVehicle_TempObjectsPlaceholder: %1", X39_MedSys_var_MedicalMenu_PutUnitIntoVehicle_TempObjectsPlaceholder],
diag_log format["X39_MedSys_var_Pain_Allow: %1", X39_MedSys_var_Pain_Allow],
diag_log format["X39_MedSys_var_Pain_AllowHealthOvercharge: %1", X39_MedSys_var_Pain_AllowHealthOvercharge],
diag_log format["X39_MedSys_var_Pain_AllowMorphineOverdoseEffect: %1", X39_MedSys_var_Pain_AllowMorphineOverdoseEffect],
diag_log format["X39_MedSys_var_Pain_Blur: %1", X39_MedSys_var_Pain_Blur],
diag_log format["X39_MedSys_var_Pain_ColorCorrections: %1", X39_MedSys_var_Pain_ColorCorrections],
diag_log format["X39_MedSys_var_Pain_GreyScreen: %1", X39_MedSys_var_Pain_GreyScreen],
diag_log format["X39_MedSys_var_Pain_GreyScreenManipulator: %1", X39_MedSys_var_Pain_GreyScreenManipulator],
diag_log format["X39_MedSys_var_Pain_HealthOverchargeEffectManipulator: %1", X39_MedSys_var_Pain_HealthOverchargeEffectManipulator],
diag_log format["X39_MedSys_var_Pain_MaxBlur: %1", X39_MedSys_var_Pain_MaxBlur],
diag_log format["X39_MedSys_var_Pain_MaxHealthOvercharge: %1", X39_MedSys_var_Pain_MaxHealthOvercharge],
diag_log format["X39_MedSys_var_Pain_Modificator: %1", X39_MedSys_var_Pain_Modificator],
diag_log format["X39_MedSys_var_Pain_MorphineAlsoHeals: %1", X39_MedSys_var_Pain_MorphineAlsoHeals],
diag_log format["X39_MedSys_var_Pain_MorphineEffectReducedPerTick: %1", X39_MedSys_var_Pain_MorphineEffectReducedPerTick],
diag_log format["X39_MedSys_var_Pain_MorphineHealValue	: %1", X39_MedSys_var_Pain_MorphineHealValue],
diag_log format["X39_MedSys_var_Pain_RedScreen: %1", X39_MedSys_var_Pain_RedScreen],
diag_log format["X39_MedSys_var_Pain_minPainToMaxPain: %1", X39_MedSys_var_Pain_minPainToMaxPain],
diag_log format["X39_MedSys_var_PreventGuiOpening: %1", X39_MedSys_var_PreventGuiOpening];
diag_log format["X39_MedSys_var_Settings_EnableCamShake: %1", X39_MedSys_var_Settings_EnableCamShake],
diag_log format["X39_MedSys_var_Settings_EnableCamShake: %1", X39_MedSys_var_Settings_EnableCamShake];
diag_log format["X39_MedSys_var_Settings_Overlay_Blood_PictureValues: %1", X39_MedSys_var_Settings_Overlay_Blood_PictureValues],
diag_log format["X39_MedSys_var_Settings_Overlay_RefreshRate: %1", X39_MedSys_var_Settings_Overlay_RefreshRate],
diag_log format["X39_MedSys_var_Settings_Overlay_Transparency: %1", X39_MedSys_var_Settings_Overlay_Transparency],
diag_log format["X39_MedSys_var_Settings_playEarRingingSound: %1", X39_MedSys_var_Settings_playEarRingingSound],
diag_log format["X39_MedSys_var_TickRate: %1", X39_MedSys_var_TickRate];
diag_log format["X39_MedSys_var_actionTimeout_BandageUnit: %1", X39_MedSys_var_actionTimeout_BandageUnit],
diag_log format["X39_MedSys_var_actionTimeout_BloodUnit: %1", X39_MedSys_var_actionTimeout_BloodUnit],
diag_log format["X39_MedSys_var_actionTimeout_CheckUnitStatus: %1", X39_MedSys_var_actionTimeout_CheckUnitStatus],
diag_log format["X39_MedSys_var_actionTimeout_DephibrilateUnit: %1", X39_MedSys_var_actionTimeout_DephibrilateUnit],
diag_log format["X39_MedSys_var_actionTimeout_EpinephrineUnit: %1", X39_MedSys_var_actionTimeout_EpinephrineUnit],
diag_log format["X39_MedSys_var_actionTimeout_MorphineUnit: %1", X39_MedSys_var_actionTimeout_MorphineUnit],
diag_log format["X39_MedSys_var_actionTimeout_PutTourniquet: %1", X39_MedSys_var_actionTimeout_PutTourniquet],
diag_log format["X39_MedSys_var_actionTimeout_Stabilize: %1", X39_MedSys_var_actionTimeout_Stabilize],
diag_log format["X39_MedSys_var_actionTimeout_UseMedkitOnUnit: %1", X39_MedSys_var_actionTimeout_UseMedkitOnUnit],
diag_log format["X39_MedSys_var_allowSpeedLimitations: %1", X39_MedSys_var_allowSpeedLimitations],	
diag_log format["X39_MedSys_var_allowSpeedLimitations_forceWalkAtXDamage: %1", X39_MedSys_var_allowSpeedLimitations_forceWalkAtXDamage],
diag_log format["X39_MedSys_var_enableCarry: %1", X39_MedSys_var_enableCarry],
diag_log format["X39_MedSys_var_enableDrag: %1", X39_MedSys_var_enableDrag],
diag_log format["X39_MedSys_var_maxDamage: %1", X39_MedSys_var_maxDamage],