#define GRID_ABS_W		0.5
#define GRID_ABS_H		0.5
#define GRID_TITLE_H 	0.05
#define GRID_COUNT_W 	100
#define GRID_COUNT_H 	100

/* Automatisch zentriert berechnen */
#define GRID_W			(GRID_ABS_W / GRID_COUNT_W)
#define GRID_H			(GRID_ABS_H / GRID_COUNT_H)
#define GRID_ABS_X		(0.5 - (GRID_ABS_W / 2))
#define GRID_ABS_Y		(0.5 - (GRID_ABS_H / 2))


/* ID's 600-649 */
#define PIXLOGISTIC_IDD_DIALOG_OBJECTCONTENT				600
#define PIXLOGISTIC_IDC_DIALOG_OBJECTCONTENT_Title 			601
#define PIXLOGISTIC_IDC_DIALOG_OBJECTCONTENT_Capacity 		602
#define PIXLOGISTIC_IDC_DIALOG_OBJECTCONTENT_List 			603
#define PIXLOGISTIC_IDC_DIALOG_OBJECTCONTENT_ButtonUnload 	604
#define PIXLOGISTIC_IDC_DIALOG_OBJECTCONTENT_ButtonMove 	605
#define PIXLOGISTIC_IDC_DIALOG_OBJECTCONTENT_ButtonCancel 	606

