#define DEFAULT_HEADGEAR			"H_HelmetB_tna_F"
#define DEFAULT_HEADGEAR_ENH		"H_HelmetB_Enh_tna_F"
#define DEFAULT_HEADGEAR_LIGHT		"H_HelmetB_Light_tna_F"
#define DEFAULT_HEADGEAR_HELI		"H_PilotHelmetHeli_B"
#define DEFAULT_HEADGEAR_JET		"H_PilotHelmetHeli_B"

#define DEFAULT_GOOGLES				"G_Combat"
#define DEFAULT_BINOCULARS			"Rangefinder"
#define DEFAULT_LASERDESIGNATOR		"Laserdesignator"
#define DEFAULT_NIGHTVISION			"NVGoggles_tna_F"
#define DEFAULT_LINKEDITEMS			"ItemMap","ItemWatch","ItemCompass","ItemGps"
#define DEFAULT_LINKEDITEMS_UAV		"ItemMap","ItemWatch","ItemCompass","B_UavTerminal"

#define DEFAULT_HANDGUNWEAPON		"hgun_P07_F"
#define DEFAULT_HANDGUNMAGAZINE		"16Rnd_9x21_Mag"
#define DEFAULT_HANDGUNITEMS		"muzzle_snds_L"

#define DEFAULT_UNIFORM				"U_B_T_Soldier_F"
#define DEFAULT_UNIFORM_FREETIME	"U_B_T_Soldier_F"
#define DEFAULT_UNIFORM_CREW		"U_B_T_Soldier_SL_F"
#define DEFAULT_UNIFORM_ENGINEER	"U_B_T_Soldier_SL_F"
#define DEFAULT_UNIFORM_HELI		"U_B_HeliPilotCoveralls"
#define DEFAULT_UNIFORM_JET			"U_B_PilotCoveralls"

#define DEFAULT_UNIFORMWEAPONS		""
#define DEFAULT_UNIFORMMAGAZINES	""
#define DEFAULT_UNIFORMITEMS		"ItemRadio", "ACE_EarPlugs", "ACE_CableTie", "ACE_CableTie", "ACE_CableTie", "ACE_CableTie", "ACE_Flashlight_MX991", "ACE_IR_Strobe_Item", "ACE_tourniquet", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_morphine", "ACE_morphine", "ACE_morphine"

#define DEFAULT_VEST				"V_TacVest_blk"
#define DEFAULT_VEST_GMG			"V_PlateCarrierGL_tna_F"
#define DEFAULT_VEST_MEDIC			"V_PlateCarrier2_tna_F"
#define DEFAULT_VEST_LMG			"V_PlateCarrier2_tna_F"
#define DEFAULT_VEST_TF				"V_PlateCarrierGL_tna_F"
#define DEFAULT_VEST_GF				"V_PlateCarrierGL_tna_F"
#define DEFAULT_VEST_SOLDIER		"V_PlateCarrier1_tna_F"
#define DEFAULT_VEST_ENIGNEERREP	"V_PlateCarrier1_tna_F"
#define DEFAULT_VEST_ENIGNEEREXP	"V_PlateCarrierIAGL_oli"
#define DEFAULT_VEST_ATNLAW			"V_PlateCarrier1_tna_F"
#define DEFAULT_VEST_AT				"V_PlateCarrier1_tna_F"
#define DEFAULT_VEST_AA				"V_PlateCarrier1_tna_F"
#define DEFAULT_VEST_SNIPERROUP		"V_PlateCarrier1_tna_F"
#define DEFAULT_VEST_CREW			"V_BandollierB_rgr"
#define DEFAULT_VEST_HELI			"V_TacVest_blk"
#define DEFAULT_VEST_JET			"V_TacVest_blk"
#define DEFAULT_VEST_UAV			"V_PlateCarrierSpec_tna_F"

#define DEFAULT_VESTWEAPONS			"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShellGreen", "SmokeShellRed", "Handgrenade", "Handgrenade"
#define DEFAULT_VESTWEAPONS_LIGHT	"SmokeShell", "SmokeShell", "SmokeShellGreen", "SmokeShellRed"
#define DEFAULT_VESTMAGAZINES		"16Rnd_9x21_Mag","16Rnd_9x21_Mag"
#define DEFAULT_VESTMAGAZINES_LIGHT	""
#define DEFAULT_VESTITEMS			""

#define DEFAULT_BACKPACK			"B_AssaultPack_tna_F"
#define DEFAULT_BACKPACKMEDIUM		"B_Carryall_oli"
#define DEFAULT_BACKPACKLARGE		"B_Bergen_tna_F"
#define DEFAULT_BACKPACKRADIO		"tf_rt1523g_bwmod"
#define DEFAULT_BACKPACKWEAPONS		""
#define DEFAULT_BACKPACKMAGAZINES	""
#define DEFAULT_BACKPACKITEMS		""
