[
	["Freizeit", 						"Default.sqf"],
	["Freizeit (Rucksack)", 			"DefaultBackpack.sqf"],	
	['Schütze',							"Soldier.sqf"],
	['Grenadier',						"GMG.sqf"],
	['Sanitäter',						"Medic.sqf"],
	['Sanitäter (Funk)',				"Medic_Radio.sqf"],
	['Pionier (Reparatur)',				"EngineerREP.sqf"],
	['Pionier (Sprengstoff)',			"EngineerEXP.sqf"],
	['Luftabwehr (Titan)',				"AA_Titan.sqf"],
	['Panzerabwehr (Titan)',			"AT_Titan.sqf"],
	['Panzerabwehr (NLAW)',				"AT_NLAW.sqf"],
	['Leichtes-MG',						"LMG.sqf"],
	['Gr.Scharfschütze',				"SniperGroup.sqf"],
	['UAV-Operator', 					"UAV.sqf"],
	['Truppführer (Hunt-IR)', 			"TF.sqf"],
	['Gruppenführer (Funk)', 			"GF.sqf"],
	['Fahrzeug-Crew',					"Crew.sqf"],
	['Pilot (Jet)', 					"PilotJet.sqf"],
	['Pilot (Heli)', 					"PilotHeli.sqf"],
	['Offizier', 						"Officer.sqf"]
];
