[
	[localize "str_pc3Gear_FreeTime", 				"Default.sqf"],
	[localize "str_pc3Gear_FreeTimeBackpack",		"DefaultBackpack.sqf"],	
	[localize 'str_pc3Gear_Soldier',				"Soldier.sqf"],
	[localize 'str_pc3Gear_Grenadier',				"GMG.sqf"],
	[localize 'str_pc3Gear_Medic',					"Medic.sqf"],
	[localize 'str_pc3Gear_MedicRadio',				"Medic_Radio.sqf"],
	[localize 'str_pc3Gear_PionierREP',				"EngineerREP.sqf"],
	[localize 'str_pc3Gear_PionierEXP',				"EngineerEXP.sqf"],
	[localize 'str_pc3Gear_AA_Titan',				"AA_Titan.sqf"],
	[localize 'str_pc3Gear_AT_Titan',				"AT_Titan.sqf"],
	[localize 'str_pc3Gear_AT_NLAW',				"AT_NLAW.sqf"],
	[localize 'str_pc3Gear_LMG',					"LMG.sqf"],
	[localize 'str_pc3Gear_SniperGroup',			"SniperGroup.sqf"],
	[localize 'str_pc3Gear_UAV', 					"UAV.sqf"],
	[localize 'str_pc3Gear_TF', 					"TF.sqf"],
	[localize 'str_pc3Gear_GFRadio', 				"GF.sqf"],
	[localize 'str_pc3Gear_Crew',					"Crew.sqf"],
	[localize 'str_pc3Gear_PilotJet', 				"PilotJet.sqf"],
	[localize 'str_pc3Gear_PilotHeli', 				"PilotHeli.sqf"],
	[localize 'str_pc3Gear_Officer', 				"Officer.sqf"]
];
