[
	["Freizeit (Unbewaffnet)", "Default.sqf"]	,
	["Soldat","rifleman.sqf"],
	["Soldat (W)","rifleman_w.sqf"],
	["Grenadier","Grenade.sqf"],
	["Grenadier (W)","Grenade_w.sqf"],
	["Sanitäter (Kämpfer)","MedicCombat.sqf"],
	["Sanitäter (W/Kämpfer)","MedicCombat_w.sqf"],
	["Sanitäter (Funk)","MedicRadio.sqf"],
	["Sanitäter (W/Funk)","MedicRadio_w.sqf"],
	["Truppführer","Teamleader.sqf"],
	["Truppführer (W)","Teamleader_w.sqf"],
	["Truppführer (Funk)","TeamleaderRadio.sqf"],
	["Truppführer (W/Funk)","TeamleaderRadio_w.sqf"],
	["Automatikschütze (Mk200)","Belt_AutoriflemanMk200.sqf"],
	["Automatikschütze (W/Mk200)","Belt_AutoriflemanMk200_w.sqf"],
	["Automatikschütze (Navid 9.3mm) DLC","Belt_AutoriflemanNavid.sqf"],
	["Automatikschütze (W/Navid 9.3mm) DLC","Belt_AutoriflemanNavid_w.sqf"],
	["Gruppenscharfschütze","GroupSniperMk18.sqf"],
	["Gruppenscharfschütze (W)","GroupSniperMk18_w.sqf"],
	["Gruppenscharfschütze (MK14) DLC","GroupSniperMk14.sqf"],
	["Gruppenscharfschütze (W/MK14) DLC","GroupSniperMk14_w.sqf"],
	["Gruppenscharfschütze (Mk-1) DLC","GroupSniperMk1.sqf"],
	["Gruppenscharfschütze (W/Mk-1) DLC","GroupSniperMk1_w.sqf"],
	["NLAW (AT)","NLAW.sqf"],
	["NLAW (W/AT)","NLAW_w.sqf"],
	["Titan (AT)","TitanAT.sqf"],
	["Titan (W/AT)","TitanAT_w.sqf"],
	["Titan (AA)","TitanAA.sqf"],
	["Titan (W/AA)","TitanAA_w.sqf"],
	["Sprengstoffexperte","EngineerMine.sqf"],
	["Sprengstoffexperte (W)","EngineerMine_w.sqf"],
	["Reparaturexperte","EngineerRepair.sqf"],
	["Reparaturexperte (W)","EngineerRepair_w.sqf"],
	["Aufklärungsexperte (DLC)","EngineerScout.sqf"],
	["Crew","Crew.sqf"],
	["Helipilot", "HeliPilot.sqf"],
	["Heli Crewchief (Radio)", "HeliCrewchief.sqf"],
	["Jetpilot", "JetPilot.sqf"],
	["Operator HALO", "OperatorHalo.sqf"],
	["Operator HALO (TF) ", "OperatorTfHalo.sqf"],
	["Operator HALO (AT)", "OperatorHaloAT.sqf"],
	["Operator UAV","OperatorUAV.sqf"],
	["Operator Aufklärer","OperatorScout.sqf"],
	["Operator MG (SPMG .338) DLC","OperatorSPMG.sqf"],
	["Operator GS (MAR10 .338) DLC","OperatorMAR10.sqf"],
	["Scharfschütze (M320 LLR)","SniperGM6.sqf"],
	["Scharfschütze (Spotter)","Spotter.sqf"],
	["Scharfschütze (Cyrus) DLC","SniperCyrus.sqf"],
	["Scharfschütze (Spotter) DLC","SpotterDLC.sqf"],
	["Aufklärer (Unbewaffnet)", "UnarmedScout.sqf"],
	["Aufklärer (ohne Hilfsmittel)", "noGpsScout.sqf"],
	["BW Freizeit (Unbewaffnet)", "BW_Default.sqf"],
	["BW Schütze (G36)","BW_SoldierG36.sqf"],
	["BW Schütze (G27)","BW_SoldierG27.sqf"],
	["BW Schütze (G28)","BW_SoldierG28.sqf"],
	["BW Grenadier (G36)","BW_GrenadeG36.sqf"],
	["BW Grenadier (G27)","BW_GrenadeG27.sqf"],
	["BW Sanitäter","BW_Medic.sqf"],
	["BW Officer","BW_Officer.sqf"],
	["BW Truppführer (AG36)","BW_Teamleader.sqf"],
	["BW Gruppenführer","BW_Squadleader.sqf"],
	["BW Automatikschütze (MG3)","BW_Belt_AutoriflemanMG3.sqf"],
	["BW Automatikschütze (MG4)","BW_Belt_AutoriflemanMG4.sqf"],
	["BW Automatikschütze (MG5)","BW_Belt_AutoriflemanMG5.sqf"],
	["BW Gruppenscharfschütze","BW_GroupSniperG28.sqf"],
	["BW PzF3 (AT)","BW_PzF3.sqf"],
	["BW RGW90","BW_RGW90.sqf"],
	["BW Titan (AT)","BW_TitanAT.sqf"],
	["BW Titan (AA)","BW_TitanAA.sqf"],
	["BW Feuerwerker (EOD)","BW_EngineerMine.sqf"],
	["BW Pionier","BW_EngineerRepair.sqf"],
	["BW Crew","BW_Crew.sqf"],
	["BW Crew (Officer)", "BW_Crewchief.sqf"],
	["BW Helipilot", "BW_HeliPilot.sqf"]
];
