[
	["BW Freizeit (Unbewaffnet)", "BW_Default.sqf"],
	["BW Freizeit (Rucksack)", "BW_DefaultBackpack.sqf"],	
	["BW Schütze (G27)","BW_SoldierG27.sqf"],
	["BW Schütze (G36)","BW_SoldierG36.sqf"],
	["BW Grenadier (G27)","BW_GrenadeG27.sqf"],
	["BW Grenadier (G36)","BW_GrenadeG36.sqf"],
	["BW Sanitäter (Kampf)","BW_Medic.sqf"],
	["BW Sanitäter (Funk)","BW_Medic_Radio.sqf"],
	["BW Automatikschütze (MG3)","BW_Belt_AutoriflemanMG3.sqf"],
	["BW Automatikschütze (MG4)","BW_Belt_AutoriflemanMG4.sqf"],
	["BW Automatikschütze (MG5)","BW_Belt_AutoriflemanMG5.sqf"],
	["BW Gruppenscharfschütze","BW_GroupSniperG28.sqf"],
	["BW Panzerabwehr (PzF3)","BW_AT_PzF3.sqf"],
	["BW Panzerabwehr (RGW90)","BW_AT_RGW90.sqf"],
	["BW Panzerabwehr (Titan)","BW_AT_Titan.sqf"],
	["BW Luftabwehr (Titan)","BW_AA_Titan.sqf"],
	["BW Pionier (Sprengstoffe)","BW_EngineerMine.sqf"],
	["BW Pionier (Reparatur)","BW_EngineerRepair.sqf"],
	["BW Pionier (Spezialist)","BW_EngineerSpecialist.sqf"],
	["BW Truppführer (Grenadier)","BW_Lead_Grenadier.sqf"],
	["BW Gruppenführer (Funk)","BW_Lead_Radio.sqf"],
	["BW Operator (UAV)","BW_Operator_UAV.sqf"],	
//	["BW Crew","BW_Crew.sqf"],
//	["BW Crew (Officer)", "BW_Crewchief.sqf"],
	["BW Helipilot", "BW_HeliPilot.sqf"],
	["BW Offizier","BW_Officer.sqf"]
];
