[
	["BW Freizeit (Unbewaffnet)", "BW_Default.sqf"],
	["BW Freizeit (Rucksack)", "BW_DefaultBackpack.sqf"],	
	["BW Schütze (G27)","BW_SoldierG27.sqf"],
	["BW Schütze (G36)","BW_SoldierG36.sqf"],
	["BW Grenadier (G27)","BW_GrenadeG27.sqf"],
	["BW Grenadier (G36)","BW_GrenadeG36.sqf"],
	["BW Sanitäter","BW_Medic.sqf"],
//	["BW Truppführer (AG36)","BW_Teamleader.sqf"],
//	["BW Gruppenführer","BW_Squadleader.sqf"],
//	["BW Automatikschütze (MG3)","BW_Belt_AutoriflemanMG3.sqf"],
//	["BW Automatikschütze (MG4)","BW_Belt_AutoriflemanMG4.sqf"],
//	["BW Automatikschütze (MG5)","BW_Belt_AutoriflemanMG5.sqf"],
	["BW Gruppenscharfschütze","BW_GroupSniperG28.sqf"],
//	["BW PzF3 (AT)","BW_PzF3.sqf"],
//	["BW RGW90","BW_RGW90.sqf"],
//	["BW Titan (AT)","BW_TitanAT.sqf"],
//	["BW Titan (AA)","BW_TitanAA.sqf"],
//	["BW Pionier (EOD)","BW_EngineerMine.sqf"],
//	["BW Pionier (REP)","BW_EngineerRepair.sqf"],
//	["BW Operator (UAV)","BW_Operator_UAV.sqf"],	
//	["BW Crew","BW_Crew.sqf"],
//	["BW Crew (Officer)", "BW_Crewchief.sqf"],
	["BW Helipilot", "BW_HeliPilot.sqf"],
	["BW Offizier","BW_Officer.sqf"]
];
