#define DEFAULT_GOOGLES				"G_Balaclava_TI_G_tna_F"
#define DEFAULT_HEADGEAR			"H_HelmetB_TI_tna_F"
#define DEFAULT_BINOCULARS			"ACE_Vector" //"Rangefinder"
#define DEFAULT_LASERDESIGNATOR		"Laserdesignator"
#define DEFAULT_NIGHTVISION			"NVGogglesB_grn_F"
#define DEFAULT_LINKEDITEMS			"ItemMap","ItemWatch","ItemCompass","ItemGps"
#define DEFAULT_LINKEDITEMS_UAV		"ItemMap","ItemWatch","ItemCompass","B_UavTerminal"

#define DEFAULT_HANDGUNWEAPON		"hgun_P07_F"
#define DEFAULT_HANDGUNMAGAZINE		"16Rnd_9x21_Mag"
#define DEFAULT_HANDGUNITEMS		"muzzle_snds_L"


#define DEFAULT_UNIFORM				"U_B_CTRG_Soldier_F"
#define DEFAULT_UNIFORM_FREETIME	"U_B_T_Soldier_F"
#define DEFAULT_UNIFORMWEAPONS		""
#define DEFAULT_UNIFORMMAGAZINES	""
#define DEFAULT_UNIFORMITEMS		"ItemRadio", "ACE_microDAGR", "ACE_EarPlugs", "ACE_CableTie", "ACE_CableTie", "ACE_CableTie", "ACE_CableTie", "ACE_Flashlight_MX991", "ACE_IR_Strobe_Item", "ACE_tourniquet", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_morphine", "ACE_morphine", "ACE_morphine"

#define DEFAULT_VEST				"V_TacVest_oli"
#define DEFAULT_VEST_GMG			"V_TacVest_oli"
#define DEFAULT_VEST_MEDIC			"V_TacVest_oli"
#define DEFAULT_VEST_MG				"V_TacVest_oli"
#define DEFAULT_VEST_TF				"V_TacVest_oli"
#define DEFAULT_VEST_GF				"V_TacVest_oli"
#define DEFAULT_VEST_SCOUT			"V_TacVest_oli"
#define DEFAULT_VEST_ENIGNEER		"V_PlateCarrierIAGL_oli"
#define DEFAULT_VEST_JTAC			"V_PlateCarrierIAGL_oli"
#define DEFAULT_VEST_AT				"V_TacVest_oli"
#define DEFAULT_VEST_SNIPERROUP		"V_TacVest_oli"
#define DEFAULT_VESTWEAPONS			"SmokeShell", "SmokeShell", "SmokeShell", "SmokeShellGreen", "SmokeShellRed", "Handgrenade", "Handgrenade"
#define DEFAULT_VESTWEAPONS_LIGHT	"SmokeShell", "SmokeShell", "SmokeShellGreen", "SmokeShellRed"
#define DEFAULT_VESTMAGAZINES		"16Rnd_9x21_Mag","16Rnd_9x21_Mag"
#define DEFAULT_VESTMAGAZINES_LIGHT	""
#define DEFAULT_VESTITEMS			""

#define DEFAULT_BACKPACK			"B_AssaultPack_tna_F"
#define DEFAULT_BACKPACKLARGE		"B_Bergen_tna_F"
#define DEFAULT_BACKPACKRADIO		"tf_rt1523g_bwmod"
#define DEFAULT_BACKPACKWEAPONS		""
#define DEFAULT_BACKPACKMAGAZINES	""
#define DEFAULT_BACKPACKITEMS		""