#define PIXLOGISTIC_IDD_DIALOG_LIFT_HUD				1000
#define PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_Background	800
#define PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_Object		801
#define PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_Height		802
#define PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_Text		803
#define PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_Ground		804

#define PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_BACKGROUND_W	(0.3)
#define PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_BACKGROUND_H	(0.3)
#define PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_BACKGROUND_X	(1 - PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_BACKGROUND_W)
#define PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_BACKGROUND_Y	(1 - PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_BACKGROUND_H)

#define PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_TEXT_W			PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_BACKGROUND_W
#define PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_TEXT_H			PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_BACKGROUND_H
#define PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_TEXT_X			PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_BACKGROUND_X
#define PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_TEXT_Y			PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_BACKGROUND_Y

#define PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_OBJECT_W		(0.01)
#define PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_OBJECT_H		(0.01)
#define PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_OBJECT_X		(PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_BACKGROUND_X + (PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_BACKGROUND_W / 2) - (PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_OBJECT_W / 2))
#define PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_OBJECT_Y		(PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_BACKGROUND_Y + (PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_BACKGROUND_H / 2) - (PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_OBJECT_H / 2))

#define PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_HEIGHT_W		(0.05)
#define PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_HEIGHT_H		(0.05)
#define PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_HEIGHT_X		(PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_BACKGROUND_X + PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_BACKGROUND_W - PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_HEIGHT_W)
#define PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_HEIGHT_Y		(PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_BACKGROUND_Y + PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_BACKGROUND_H - PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_HEIGHT_H)

#define PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_GROUND_W		(0.05)
#define PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_GROUND_H		(0.05)
#define PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_GROUND_X		(PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_BACKGROUND_X + (PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_BACKGROUND_W / 2))
#define PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_GROUND_Y		(PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_BACKGROUND_Y + PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_BACKGROUND_H - PIXLOGISTIC_IDC_DIALOG_LIFT_HUD_GROUND_H)
